[project]
name = "stt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faster-whisper>=1.1.1",
    "quart>=0.20.0",
    "quart-cors>=0.8.0",
    "torch>=2.7.1",
]
